### ISSUE TITLE
Ch 2: Change name of this chapter?

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#173]
"Planning data work", since it should also be applicable to non-field-related data?

**Comment by mariaruth** [comment]
I had the same comment - also because there isn't any content about data collection per se (e.g. designing forms, data quality checks, etc). Perhaps "Planning data work from the start of a project". it's way too long but i'd like to call this something like : "An ounce of prevention is worth a pound of cure: the benefits of planning data work"

**Comment by mariaruth** [comment]
change to "Collaborating on Code and Data"
