### ISSUE TITLE
Ch2: Introduction and chapter set-up

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#185]
I got a bit lost with the organization of the chapter. right now the outline is:
2.1 Preparing your digital workspace
2.1.1 Setting up your computer
2.1.2 Folder management
2.1.3 Code management
2.1.4 Version control
2.1.5 Output management
2.1.6 Preparing for collaboration and replication

We need some more sections, and a preview of the structure of the chapter in the intro so the reader has a guide.

**Comment by mariaruth** [comment]
Suggested structure:

2.1 Preparing your digital workspace
2.1.1 Setting up your computer
2.1.2 Software choices
2.2 Coding in a team
2.2.1 Folder management
2.2.2 Code management
2.3 Version Control

**Comment by kbjarkefur** [comment]
Suggested structure:

2.1 Initial Setup / Things to discuss before getting started
2.1.1 Setting up your computer
2.1.2 Software choices
2.2 Folder management
2.3 Code management
2.3.1 Version Control
2.3.1 Output Management

**Comment by luizaandrade** [comment]
I have: 

2.1 Initial setup
2.1.1 Setting up your computer
2.1.2 Agree on task management and decision documentation (not e-mail)!
2.1.3. Software coices
- Assume primary data on Stata because
    - that’s what we use more commonly
    - Stata does not have as many resources developed
- Non-conventional data 
    - servers
    - computer capacity
    - software
2.2 Folder management
2.2.1 Naming conventions
2.3 Code management
2.3.1 Version control
2.3.2 Output management
