### ISSUE TITLE
Ch 5: suggested structure

### ISSUE THREAD

**Issue by luizaandrade** [worldbank/d4di#264]
**Intro**
- Diagram of timeline/tasks in all the field work
- Discuss RA and FC roles
- What is the focus of the chapter: how the data collection and the data work interact

**Design**
- Research design and questionnaire design
   - Attrition
   - Preloads
- Questionnaire design and data
   - What are the final indicators of interest
   - What variables do we need to build them
   - How these variables translate into questions

**Programming the survey**
- Variable names
- What data is needed as input
   - IDs
   - Master data set (listing)
   - Final sample
- List sensitive variables (decide on publishable fields)
- Think of the relevant checks to be run

**Data quality monitoring**
- Duplicates
- Logbook
- Back checks
- HFCs
- Corrections

**Data security**

**Comment by kbjarkefur** [comment]
For questionnaire design, do not try to replicate the great survey design guides that are already out there, instead:
* focus on work flow over content. I.e. talk about paper questionnaire before code etc.
* how to structure a survey so that the data that comes out of the survey is well structured

Also, this chapter should focus on the data aspect of data collection, and not so much on the field management.

**Comment by mariaruth** [comment]
addressed in edits in #310
