### ISSUE TITLE
Ch6: overall content

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#270]
This chapter feels a little thin, but I can't put a finger on why/what's missing. Also - a little misaligned with the title in that only about 1/3 has to do with data analysis, but the content on organizing data and cleaning / constructing is certainly useful (perhaps want to adjust the title). 

A few questions to discuss:

1. The focus is on primary survey data - should we generalize to also apply to admin / secondary data?

2. The treatment of any of the topics (data cleaning, variable construction, data analysis, data viz) seems rather cursory. But perhaps we want that as we are primarily pointing to other existing resources. We should think more about exactly what our angle / value-add is on this topic.

**Comment by bbdaniels** [comment]
See #269

**Comment by kbjarkefur** [comment]
When I do my intro to coding presentation I say: 

> In coding, analysis is easy as long as you have organized your data well.

The "_In coding_" means that analysis is difficult _in econometrics_, but not in coding if you have organized your data well. Since this is not a book on econometrics, then this chapter should focus a lot on how to prepare your data for analysis, cause if your data is prepared well, then it is easy to use the commands already prepared for you in Stata, R etc. to do the analysis. Which command to use is an econometrics question.

This is in line with the structure you are suggesting @bbdaniels , but I think this needs to be made more clear to a reader who is new to this way of thinking about data analysis.
