### ISSUE TITLE
Ch6: analysis dataset

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#273]
I disagree that one should never create a canonical analysis dataset! it depends on the project and the data structure, but there are some cases in which all the analysis is at the same level and then this works just fine.

**Comment by bbdaniels** [comment]
See response on #274

**Comment by kbjarkefur** [comment]
- discuss when it is better to have multiple data sets instead of a canonical data set with variables indicating different samples - @bbdaniels has examples for when multiple data sets are better
- discuss methods for how to ensure that you are using the correct sample if you are using a canonical dataset
- use macros in master do-file to indicate samples. this is very dynamic and easy to update in all files if needed
