### ISSUE TITLE
Ch3: cross-sectional designs

### ISSUE THREAD

**Issue by mariaruth** [worldbank/d4di#397]
I'm still struggling with the flow of the cross-sectional designs subsection. i understand that the motivation is to include both experiment/non-experimental methods here and in diff-diff. it works in diff-diff. but here i get thrown off. perhaps because quasi-experimental designs are never going to be purely cross-sectional in terms of research design, they have to have some sort of identification strategy, i.e. you could collect cross-sectional data for a quasi-experimental study that uses matching for identification. it doesn't feel separable from the methods that come later. whereas for an RCT cross-section is sufficient. 

does that make sense? i'm leaving that section largely unedited in my review as I think better to discuss first / @bbdaniels to revise since he wrote the original.

**Comment by bbdaniels** [comment]
I don't understand the comment here at all -- cross-sectional data with regression is absolutely sufficient for any kind of design as long as you control for OVB on whatever your "treatment" is. The RCT argument is basically "you can't". But plenty of papers do have data from only one period and estimate marginal effects based on partialling out everything that is plausibly correlated with the treatment. The only stuff I know really well is the natural disaster literature -- you never have two periods because you only collect data ex post based on where something happened, so you have to build a careful argument about exactly who is the conditional control for the affected and observed group using only one period data. It's not any of the other designs -- it's just a single cross-section with ordinary econometrics. The only point of RCT is to say definitively that you have controlled everything, but that's absolutely not needed to use this type of data.

**Comment by mariaruth** [comment]
ah, i see now where you're trying to go. but i didn't -- so do need some clarification in the text. certainly my sense that while this is done a lot in some fields, it's actually pretty uncommon / unfashionable these days in development...

**Comment by mariaruth** [comment]
i think my confusion comes because what you just described to me are non-experimental methods. Different from quasi-experimental methods. And not as clearly related to the rest of the chapter content.

**Comment by bbdaniels** [comment]
But quasi experimental methods are just non experimental methods, with a regression structure that makes them equivalent to an experimental design. Which is exactly what that is, in a cross sectional context? It may be hard and unfashionable but it's still a correct and useful approach to be familiar with and include since it's the basis of regression theory 😅

**Comment by mariaruth** [comment]
I hear you - but we define quasi experimental methods in the section before relying on 
> ``experiments of nature'', in which natural variation can be argued to approximate the type of exogenous variation in treatment availability. 
so there's a bit of a jump here. not saying we should take this out of the section, just needs some clarification

**Comment by bbdaniels** [comment]
lemme think on it... it's definitely just another one of those things where something is making sense in my head but not making it onto the page!

**Comment by bbdaniels** [comment]
@mariaruth  is this resolved by the update?

**Comment by mariaruth** [comment]
@bbdaniels - yes!
